core/src/main/scala/japgolly/scalajs/react/Addons.scala, core/src/main/scala/japgolly/scalajs/react/React.scala, test/src/test/scala/japgolly/scalajs/react/CoreTest.scala
http://facebook.github.io/react/docs/clone-with-props.html
=> ReactCloneWithProps addon and isMounted guard for async calls

doc/CHANGELOG-0.8.md, extra/README.md, extra/src/main/scala/japgolly/scalajs/react/extra/SetInterval.scala, gh-pages/src/main/scala/ghpages/ExtrasExamples.scala
I vote for changing method signature, but we could also add this in *addition* to the Double method.
=> Change SetInterval to take FiniteDuration instead of Double.

core/src/main/scala/japgolly/scalajs/react/vdom/HtmlAttrs.scala, doc/CHANGELOG-0.8.md, gh-pages/src/main/scala/ghpages/examples/TouchExample.scala, gh-pages/src/main/scala/ghpages/pages/ExamplesPage.scala, project/Build.scala
Touch events as described in:
https://facebook.github.io/react/docs/events.html
=> Added Touch event attributes and example with Touch events

README.md, core/src/main/scala/japgolly/scalajs/react/Addons.scala, core/src/main/scala/japgolly/scalajs/react/package.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Scalatags.scala, doc/CHANGELOG-0.8.md, project/Build.scala, test/src/test/scala/japgolly/scalajs/react/CoreTest.scala, test/src/test/scala/japgolly/scalajs/react/TestUtil.scala, test/src/test/scala/japgolly/scalajs/react/test/TestTest.scala
Resubmitting to 0.9 as per #123.
=> change TopNode from dom.html.Element to dom.Element (0.9)

test/src/test/scala/japgolly/scalajs/react/test/TestTest.scala
=> test event handling

extra/src/main/scala/japgolly/scalajs/react/extra/Reusability.scala, test/src/test/scala/japgolly/scalajs/react/extra/ReusabilityTest.scala
Float/Double withPrecision plus js.Date/java.util.Date/UUID cause I use those types all the time.  Up to you though.
=> Add reusability with precision + js.Date/java.util.Date/UUID

core/src/main/scala/japgolly/scalajs/react/ReactComponentB.scala
seems this was lost at some point
=> Fix ComponentWillReceiveProps

README.md
Finally got my PR merged at todomvc after quite a while. will update it to 0.10 too, so i figured it's a more useful link
=> Link to todomvc.com

core/src/main/scala/japgolly/scalajs/react/Addons.scala
PR for #198 
https://facebook.github.io/react/docs/animation.html
https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroup.js#L53-L58
=> Addons: Added support for {Appear,Enter,Leave}Timeout optional props to ReactCSSTransitionGroup case class

core/src/main/scala/japgolly/scalajs/react/vdom/Extra.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Implicits.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Scalatags.scala, core/src/main/scala/japgolly/scalajs/react/vdom/package.scala, doc/CHANGELOG-0.10.md, extra/src/main/scala/japgolly/scalajs/react/extra/router/RouterCtl.scala
=> More specific types for ReactTag

core/src/main/scala/japgolly/scalajs/react/React.scala
=> Added React.Children.toArray

doc/USAGE.md
Based on @ebruchez explanation in Gitter: https://gitter.im/japgolly/scalajs-react?at=5668e4d4c4b3d2a52a6b3d04
=> Expand section explaining role of the backend

gh-pages/src/main/scala/ghpages/examples/WebSocketsExample.scala, gh-pages/src/main/scala/ghpages/pages/ExamplesPage.scala
This PR contains a Scala ReactJS example using WebSockets connecting to the well-known WebSockets echo service at http://www.websocket.org/echo.html
I'm still learning my way around scalajs-react. I welcome any comments on my code as it may be not as idiomatic as it should be, in particular I'm not sure about having the `WebSocket` object inside the `State` class.
Does it need some type of copyright note?
=> Example using the WebSockets API

extra/src/main/scala/japgolly/scalajs/react/extra/router/RouterConfig.scala
=> Support changing <title> on route change 

core/src/main/scala/japgolly/scalajs/react/package.scala, doc/changelog/0.11.3.md
for example someRef(scope).tryTo(_.scrollIntoView())
=> generalize tryFocus to tryTo

test/src/main/scala/japgolly/scalajs/react/test/package.scala, test/src/test/scala/japgolly/scalajs/react/test/TestTest.scala
This adds the ability to render React components into the body and document which then wait for a Future to complete before unmounting and doing cleanup. This works well with the Dsl.Future in [test-state](https://github.com/japgolly/test-state). It was the recommended improvement to address issue https://github.com/japgolly/test-state/issues/7.
=> Allow asynchronously rendering a React component into the body and document

build.sbt, cats/src/main/scala/japgolly/scalajs/react/CatsReact.scala, cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactExt.scala, cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactInstances.scala, cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactState.scala, project/Build.scala, test/src/test/scala/japgolly/scalajs/react/CatsTest.scala, test/src/test/scala/japgolly/scalajs/react/MonocleTest.scala, test/src/test/scala/japgolly/scalajs/react/test/InferenceUtil.scala
Took the liberty of writting an "extra" module with integration between ScalaJS-React and Cats. I did not port yet the `Fix` type in the state extension but it should be easy to add it. Just want to make this PR to start getting some feedback.
Any ideas on how to test this could would be grateful, I did not find any tests in the same module for Scalaz.
=> Support for cats

doc/USAGE.md
Needed to use curried parameters.
=> Fix the NoArgs component creation example

doc/changelog/1.0.0.md
Please, correct me if I'm wrong somewhere...
=> Add a note about evaluation semantics of conditional rendering sugar.

doc/USAGE.md
Hi!
I've added some additional information regarding the required sbt settings when using scalajs-bundler. The link you provide is great, but it took me some time to learn about the `npmDevDependencies` setting.
Thanks for all the effort you put into scalajs-react, I really enjoy exploring it!
=> added sample sbt scalajs-bundler settings.

doc/ROUTER.md
Just a small fix for ROUTER documentation
=> Escape vertical bar

README.md
Hi, I wrote a very simple template that contains everything you need to develop and even the beginner can figure it out.
=> add simple boilerplate

README.md, build.sbt, doc/EXTRA.md, doc/FP.md, doc/PERFORMANCE.md, doc/ROUTER.md, doc/TESTING.md, doc/USAGE.md, doc/changelog/0.11.5.md, project/plugins.sbt
@japgolly Let me know when you manage to deploy this
=> Updated to 0.11.5 (bumps Scala.js version to 0.6.18)

doc/USAGE.md
Addresses https://github.com/japgolly/scalajs-react/issues/362
=> update docs for zoomState usage

doc/changelog/1.1.1.md, extra/src/main/scala/japgolly/scalajs/react/extra/StateSnapshot.scala, monocle/src/main/scala/japgolly/scalajs/react/internal/MonocleExtStateSnapshot.scala
=> Add xmap/zoom to StateSnapshot instances

core/src/main/scala/japgolly/scalajs/react/vdom/Implicits.scala, core/src/main/scala/japgolly/scalajs/react/vdom/TagMod.scala, doc/VDOM.md, doc/changelog/1.1.1.md, test/src/test/scala/japgolly/scalajs/react/core/vdom/PrefixedTest.scala, test/src/test/scala/japgolly/scalajs/react/core/vdom/UnprefixedTest.scala
=> Add .mkTagMod

gh-pages/src/main/scala/ghpages/examples/HelloMessageExample.scala, gh-pages/src/main/scala/ghpages/examples/ProductTableExample.scala, gh-pages/src/main/scala/ghpages/examples/RefsExample.scala, gh-pages/src/main/scala/ghpages/examples/TimerExample.scala, gh-pages/src/main/scala/ghpages/examples/TodoExample.scala
Hi,
i've made some changes to gh-pages examples:
- update js examples code (using functional components, classes and jsx syntax)
- change ScalaComponent to ScalaFnComponent in some places
=> gh-pages examples update

core/src/main/scala/japgolly/scalajs/react/Callback.scala, core/src/main/scala/japgolly/scalajs/react/CallbackOption.scala, doc/changelog/1.2.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/Reusable.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactExt.scala, test/src/test/scala/japgolly/scalajs/react/extra/ReusableTest.scala
=> Add Reusable.callback{,Option}ByRef

doc/PERFORMANCE.md, doc/changelog/1.2.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/Reusability.scala, test/src/test/scala/japgolly/scalajs/react/extra/ReusabilityTest.scala
Adds Reusability#logNonReusable wrapper to aid quick debugging.
=> Add Reusability#logNonReusable, addresses #421

README.md
I thought I could mention some of the facades I've built
=> Mention react component facades

cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactExt.scala, cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactInstances.scala, core/src/main/scala/japgolly/scalajs/react/Callback.scala, core/src/main/scala/japgolly/scalajs/react/CallbackKleisli.scala, doc/FP.md, doc/changelog/1.2.0.md, project/Build.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactExt.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactInstances.scala
=> Add CallbackKleisli

core/src/main/scala/japgolly/scalajs/react/CallbackKleisli.scala, doc/changelog/1.2.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/Ajax.scala, gh-pages/src/main/scala/ghpages/examples/AjaxExample.scala, gh-pages/src/main/scala/ghpages/pages/ExamplesPage.scala
=> Add Callback-integrated AJAX helper

core/src/main/scala/japgolly/scalajs/react/component/InspectRaw.scala, core/src/main/scala/japgolly/scalajs/react/component/Js.scala, core/src/main/scala/japgolly/scalajs/react/component/JsFn.scala, core/src/main/scala/japgolly/scalajs/react/component/ScalaFn.scala, doc/changelog/1.2.0.md, project/Build.scala, test/src/test/scala/japgolly/scalajs/react/core/JsComponentEs6Test.scala
Closes: #430 #431
Related: #427
=> Add much more detail to JS component check errors

doc/changelog/1.2.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/StateSnapshot.scala, gh-pages/src/main/scala/ghpages/examples/ReuseExample.scala, test/src/main/scala/japgolly/scalajs/react/test/ReactTestVar.scala, test/src/test/scala/japgolly/scalajs/react/extra/StateSnapshotTest.scala
=> Support all setState shapes in StateSnapshot

doc/changelog/1.2.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/Px.scala
=> Add Px.ManualCollection

doc/changelog/1.2.1.md, extra/src/main/scala/japgolly/scalajs/react/extra/ReusabilityOverlay.scala, gh-pages/src/main/scala/ghpages/examples/util/ErrorHandler.scala, gh-pages/src/main/scala/ghpages/pages/ExampleComponents.scala
=> Fix shouldComponentUpdateWithOverlay React16 bug

core/src/main/scala/japgolly/scalajs/react/vdom/HtmlStyles.scala, doc/changelog/1.2.1.md
This is my attempt at resolving https://github.com/japgolly/scalajs-react/issues/436.
=> CSS grid styles, resolving issue #436

doc/changelog/1.2.1.md, project/Build.scala
Just a bump on cats library versions
=> Update cats version

core/src/main/scala/japgolly/scalajs/react/ComponentDom.scala, core/src/main/scala/japgolly/scalajs/react/ReactDOM.scala, core/src/main/scala/japgolly/scalajs/react/component/Generic.scala, core/src/main/scala/japgolly/scalajs/react/component/Js.scala, core/src/main/scala/japgolly/scalajs/react/component/builder/Lifecycle.scala, core/src/main/scala/japgolly/scalajs/react/package.scala, core/src/main/scala/japgolly/scalajs/react/raw/ReactDOM.scala, doc/changelog/1.3.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/EventListener.scala, extra/src/main/scala/japgolly/scalajs/react/extra/ReusabilityOverlay.scala, extra/src/main/scala/japgolly/scalajs/react/extra/components/TriStateCheckbox.scala, gh-pages/src/main/scala/ghpages/examples/util/CodeSnippets.scala, test/src/main/scala/japgolly/scalajs/react/test/ReactTestUtils.scala, test/src/main/scala/japgolly/scalajs/react/test/package.scala, test/src/test/scala/japgolly/scalajs/react/MiscTest.scala, test/src/test/scala/japgolly/scalajs/react/core/JsComponentEs6Test.scala, test/src/test/scala/japgolly/scalajs/react/core/RawComponentEs6Test.scala, test/src/test/scala/japgolly/scalajs/react/core/RefTest.scala, test/src/test/scala/japgolly/scalajs/react/core/ScalaComponentTest.scala, test/src/test/scala/japgolly/scalajs/react/extra/EventListenerTest.scala, test/src/test/scala/japgolly/scalajs/react/extra/router/Router2Test.scala, test/src/test/scala/japgolly/scalajs/react/extra/router/RouterTest.scala, test/src/test/scala/japgolly/scalajs/react/test/ReactTestVarTest.scala, test/src/test/scala/japgolly/scalajs/react/test/TestTest.scala
=> Add ComponentDom and revise .getDOMNode semantics

cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactInstances.scala, core/src/main/scala/japgolly/scalajs/react/React.scala, core/src/main/scala/japgolly/scalajs/react/Ref.scala, core/src/main/scala/japgolly/scalajs/react/component/Generic.scala, core/src/main/scala/japgolly/scalajs/react/component/InspectRaw.scala, core/src/main/scala/japgolly/scalajs/react/component/Js.scala, core/src/main/scala/japgolly/scalajs/react/component/JsFn.scala, core/src/main/scala/japgolly/scalajs/react/component/JsForwardRef.scala, core/src/main/scala/japgolly/scalajs/react/component/ScalaForwardRef.scala, core/src/main/scala/japgolly/scalajs/react/internal/package.scala, core/src/main/scala/japgolly/scalajs/react/package.scala, core/src/main/scala/japgolly/scalajs/react/raw/React.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Attr.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Tag.scala, doc/INTEROP.md, doc/REFS.md, doc/changelog/1.3.0.md, project/Build.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactInstances.scala, test/src/test/resources/forward-ref.js, test/src/test/scala/japgolly/scalajs/react/core/JsLikeComponentTest.scala, test/src/test/scala/japgolly/scalajs/react/core/RefTest.scala, test/src/test/scala/japgolly/scalajs/react/test/InferenceUtil.scala, test/src/test/scala/japgolly/scalajs/react/test/TestUtil.scala
=> Ref forwarding

core/src/main/scala/japgolly/scalajs/react/Ref.scala, core/src/main/scala/japgolly/scalajs/react/component/InspectRaw.scala, core/src/main/scala/japgolly/scalajs/react/component/Js.scala, core/src/main/scala/japgolly/scalajs/react/component/JsFn.scala, core/src/main/scala/japgolly/scalajs/react/component/JsForwardRef.scala, core/src/main/scala/japgolly/scalajs/react/internal/JsUtil.scala, core/src/main/scala/japgolly/scalajs/react/internal/package.scala, doc/changelog/1.3.0.md, test/src/test/scala/japgolly/scalajs/react/MiscTest.scala
=> Avoid attempting toString to js.Symbol

README.md
It's the little things that count, right?! :-)
=> Minor addition of missing word in README

core/src/main/scala/japgolly/scalajs/react/vdom/HtmlAttrs.scala, doc/changelog/1.4.0.md
Adds support for form attribute: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fae-form
=> Form support take2

core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala, doc/changelog/1.4.2.md
=> Add AsyncCallback.fromCallback

core/src/main/scala/japgolly/scalajs/react/vdom/HtmlStyles.scala, doc/changelog/1.4.2.md
=> Fix CSS-Grid style definitions to not cause React warnings

core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala, doc/changelog/1.4.2.md
=> Fix key+ref in fullOptJS

core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala, core/src/main/scala/japgolly/scalajs/react/internal/SyncPromise.scala, doc/changelog/1.4.2.md, test/src/test/scala/japgolly/scalajs/react/core/AsyncCallbackTest.scala
=> Make AsyncCallback.promise synchronous once completed

README.md, doc/CONTEXT.md
This is actually working on my application, I thought I'd save others the hassle of figuring it out. Let me know if you think I got it right.
=> A little bit of documentation for how to use ReactContext

doc/ROUTER.md, doc/changelog/1.5.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala, test/src/test/scala/japgolly/scalajs/react/extra/router/DslTest.scala, test/src/test/scala/japgolly/scalajs/react/extra/router/RouterTest.scala, test/src/test/scala/japgolly/scalajs/react/test/TestUtil.scala
=> Add queryToMap to Router DSL

doc/changelog/1.5.0.md, test/src/main/scala/japgolly/scalajs/react/test/TestBroadcaster.scala
=> Add TestBroadcaster

core/src/main/scala/japgolly/scalajs/react/Reusable.scala, doc/changelog/1.5.0.md
=> Add Reusable.fnOutput

doc/ROUTER.md, doc/changelog/1.5.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/Router.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/RouterConfig.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/RoutingRule.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/RoutingRules.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/Rule.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/StaticOrDynamic.scala, extra/src/main/scala/japgolly/scalajs/react/extra/router/package.scala, monocle-cats/src/main/scala/japgolly/scalajs/react/MonocleReact.scala, monocle-scalaz/src/main/scala/japgolly/scalajs/react/MonocleReact.scala, monocle/src/main/scala/japgolly/scalajs/react/MonocleReact.scala, project/Build.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactInstances.scala, test/src/test/resources/polyfill.js, test/src/test/scala/japgolly/scalajs/react/extra/router/Router2Test.scala, test/src/test/scala/japgolly/scalajs/react/extra/router/RouterTest.scala
=> Allow conditional route overlap

core/src/main/scala/japgolly/scalajs/react/package.scala, doc/changelog/1.5.1.md
=> Add top-level preventDefault/stopPropagation fns

core/src/main/scala/japgolly/scalajs/react/ReactCaughtError.scala, core/src/main/scala/japgolly/scalajs/react/component/builder/Lifecycle.scala, core/src/main/scala/japgolly/scalajs/react/component/builder/ViaReactComponent.scala, core/src/main/scala/japgolly/scalajs/react/raw/React.scala, doc/changelog/1.6.0.md, gh-pages/src/main/scala/ghpages/examples/util/ErrorHandler.scala
=> Revise .componentDidCatch

doc/VDOM.md
Typo in documentation about collections.
=> Typo in VDOM.md

cats-effect/src/main/scala/japgolly/scalajs/react/effects/AsyncCallbackEffects.scala, cats-effect/src/test/scala/japgolly/scalajs/react/effects/AsyncCallbackEffectsSpec.scala, core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala, core/src/main/scala/japgolly/scalajs/react/Callback.scala, core/src/main/scala/japgolly/scalajs/react/internal/Trampoline.scala, doc/changelog/1.6.1.md, gh-pages/src/main/scala/ghpages/examples/AjaxExample2.scala, gh-pages/src/main/scala/ghpages/secret/tests/AsyncTest.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactExt.scala, test/src/test/scala/japgolly/scalajs/react/core/AsyncCallbackTest.scala, test/src/test/scala/japgolly/scalajs/react/core/CallbackTest.scala, test/src/test/scala/japgolly/scalajs/react/core/StackSafety.scala
=> Stack safety for {,Async}Callback

.travis.yml, core/src/main/scala/japgolly/scalajs/react/CtorType.scala, core/src/main/scala/japgolly/scalajs/react/ReactCaughtError.scala, core/src/main/scala/japgolly/scalajs/react/component/InspectRaw.scala, core/src/main/scala/japgolly/scalajs/react/component/Js.scala, core/src/main/scala/japgolly/scalajs/react/component/JsFn.scala, core/src/main/scala/japgolly/scalajs/react/component/ScalaFn.scala, core/src/main/scala/japgolly/scalajs/react/component/ScalaForwardRef.scala, core/src/main/scala/japgolly/scalajs/react/internal/JsRepr.scala, core/src/main/scala/japgolly/scalajs/react/package.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Implicits.scala, gh-pages/src/main/scala/ghpages/GhPages.scala, js-sandbox/index.html, js-sandbox/lifecycle-1.js, project/Build.scala, project/InBrowserTesting.scala, project/plugins.sbt, test/src/main/scala/japgolly/scalajs/react/test/SimEvent.scala, test/src/test/scala/japgolly/scalajs/react/core/ScalaComponentTest.scala, test/src/test/scala/japgolly/scalajs/react/core/internal/JsReprTest.scala
=> Scala.JS 1.0 support

core/src/main/scala/japgolly/scalajs/react/component/Js.scala, core/src/main/scala/japgolly/scalajs/react/component/JsForwardRef.scala, core/src/main/scala/japgolly/scalajs/react/package.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Tag.scala, doc/changelog/1.7.0.md, test/src/test/scala/japgolly/scalajs/react/core/RefTest.scala
=> Optional refs

core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala, core/src/main/scala/japgolly/scalajs/react/SetStateFns.scala, core/src/main/scala/japgolly/scalajs/react/StateAccess.scala, core/src/main/scala/japgolly/scalajs/react/component/builder/Lifecycle.scala, core/src/main/scala/japgolly/scalajs/react/internal/Effect.scala, doc/changelog/1.7.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/StateSnapshot.scala, scalaz-7.2/src/main/scala/japgolly/scalajs/react/internal/ScalazReactInstances.scala, test/src/test/scala/japgolly/scalajs/react/core/ScalaComponentTest.scala
=> Add async versions of all the setState functions

doc/changelog/1.7.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/StateSnapshot.scala, gh-pages/src/main/scala/ghpages/examples/StateSnapshotExample1.scala, gh-pages/src/main/scala/ghpages/examples/StateSnapshotExample2.scala, gh-pages/src/main/scala/ghpages/pages/ExamplesPage.scala, test/src/test/scala/japgolly/scalajs/react/StateSnapshotTest.scala
=> Improve and clarify StateSnapshot zooming with reuse

.travis.yml, bin/ci, bin/test-elision, core/src/main/scala/japgolly/scalajs/react/Reusability.scala, core/src/main/scala/japgolly/scalajs/react/ScalaJsReactDevConfig.scala, doc/PERFORMANCE.md, doc/changelog/1.7.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/ReusabilityOverlay.scala, test/src/test/scala/japgolly/scalajs/react/ElisionTest.scala
=> Add ScalaJsReactDevConfig and global overriding of Reusability.shouldComponentUpdate

doc/changelog/1.7.0.md, monocle-cats/src/main/scala/japgolly/scalajs/react/MonocleReact.scala, monocle-scalaz/src/main/scala/japgolly/scalajs/react/MonocleReact.scala, monocle-scalaz/src/main/scala/japgolly/scalajs/react/internal/MonocleExtComponent.scala, monocle-scalaz/src/main/scala/japgolly/scalajs/react/internal/MonocleModifier.scala, monocle-scalaz/src/main/scala/japgolly/scalajs/react/internal/MonocleOptionalModifier.scala
=> Support all kinds of optics in modState{,Option}L

core/src/main/scala/japgolly/scalajs/react/Reusability.scala, core/src/main/scala/japgolly/scalajs/react/internal/MacroUtils.scala, core/src/main/scala/japgolly/scalajs/react/internal/ReusabilityMacros.scala, doc/changelog/1.7.1.md, project/Build.scala, test/src/test/scala/japgolly/scalajs/react/core/ReusabilityTest.scala
=> Handle recursive data types in Reusability.derive

core/src/main/scala/japgolly/scalajs/react/ReactDOM.scala, core/src/main/scala/japgolly/scalajs/react/component/builder/Lifecycle.scala, core/src/main/scala/japgolly/scalajs/react/internal/NotAllowed.scala, doc/changelog/1.7.1.md, extra/src/main/scala/japgolly/scalajs/react/extra/StateSnapshot.scala, gh-pages/src/main/scala/ghpages/examples/StateSnapshotExample2.scala, monocle-scalaz/src/main/scala/japgolly/scalajs/react/internal/MonocleExtStateSnapshot.scala, monocle/src/main/scala/japgolly/scalajs/react/internal/MonocleExtStateSnapshot.scala, test/src/test/scala/japgolly/scalajs/react/StateSnapshotTest.scala
=> Fix: zooming from StateSnapshot instances causes stale data 

doc/PERFORMANCE.md
=> Fix reusability override doc

project/Build.scala, project/Lib.scala
=> Disable monocle3 module on Scala 2.12

core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
We are needing these when creating facades for libs that return attributes or ref functions to be applied to children components, so maybe someone else finds them useful.
Example: https://github.com/rpiaggio/scalajs-react-beautiful-dnd/blob/master/facade/src/main/scala/react/beautifuldnd/Draggable.scala#L38
=> Builder helpers for adding an object containing attributes and a Ref function

project/Dependencies.scala
Note the org change for monocle
=> Update Monocle3 to RC2

.github/workflows/ci.yml, coreGeneric/src/main/scala/japgolly/scalajs/react/component/InspectRaw.scala, util/src/main/scala/japgolly/scalajs/react/util/Util.scala
=> Fix linking with Java 14

coreGeneric/src/main/scala-2/japgolly/scalajs/react/internal/ReusabilityMacros.scala, coreGeneric/src/main/scala-3/japgolly/scalajs/react/ReusabilityMacros.scala, doc/changelog/2.0.0.md, tests/src/test/scala/japgolly/scalajs/react/core/ReusabilityTest.scala
=> Include Reusability.byRef in derivation

doc/ROUTER.md, doc/changelog/2.0.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala, tests/src/test/scala/japgolly/scalajs/react/extra/router/DslTest.scala
=> Add router DSL to handle repeated query params

coreGeneric/src/main/scala/japgolly/scalajs/react/SetStateFns.scala, coreGeneric/src/main/scala/japgolly/scalajs/react/StateAccess.scala, doc/changelog/2.0.0.md, downstream-tests/js/src/main/scala/downstream/Exports.scala, util/src/main/scala/japgolly/scalajs/react/util/Effect.scala
=> Expose default sync effect instead of internal type in StateFns

coreGeneric/src/main/scala/japgolly/scalajs/react/SetStateFns.scala, doc/changelog/2.0.0.md, tests/src/test/scala/japgolly/scalajs/react/extra/StateSnapshotTest.scala
=> StateSnapshot constructors should accept SetStateFns

coreGeneric/src/main/scala/japgolly/scalajs/react/internal/EffectUtil.scala, doc/changelog/2.0.0.md, extra/src/main/scala/japgolly/scalajs/react/extra/internal/TriStateCheckboxF.scala, tests/src/test/scala/japgolly/scalajs/react/extra/TriStateCheckboxTest.scala
=> Fix TriStateCheckbox onKeyDown calling preventDefault()

doc/changelog/2.0.0.md, project/Dependencies.scala
=> Fix polymorphic renderBackend in Scala 3

coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/CustomHook.scala, doc/changelog/2.0.1.md, tests/src/test/scala/japgolly/scalajs/react/core/HooksTest.scala, tests/src/test/scala/japgolly/scalajs/react/core/ScalaFnComponentTest.scala
=> Fix infinite loop in functional components with reuse + `Reusability.never`

ghpages/src/main/scala/ghpages/examples/CatsEffectExample.scala, ghpages/src/main/scala/ghpages/pages/ExamplesPage.scala, project/Build.scala
=> Add a Cats Effect demo

README.md, doc/changelog/2.1.0.md, project/plugins.sbt, version.sbt
#1037 is looking like it's going to need a minor ver bump. Will start with this....
=> Upgrade Scala.js to 1.8.0

doc/HOOKS.md, doc/changelog/2.2.0-betas.md, library/coreGeneric/src/main/scala/japgolly/scalajs/react/React.scala, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/Api.scala, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/Hooks.scala, library/facadeMain/src/main/scala/japgolly/scalajs/react/facade/Hooks.scala, library/facadeMain/src/main/scala/japgolly/scalajs/react/facade/React.scala, library/tests/src/test/scala/japgolly/scalajs/react/core/HooksTest.scala, library/tests/src/test/scala/japgolly/scalajs/react/test/DomTester.scala
- Add useId hook
- Add useTransition hook
=> react 18 hooks
