core/src/main/scala/japgolly/scalajs/react/vdom/SvgAttrs.scala
This fixes react ignoring those attributes and printing warnings like `Warning: Unknown DOM property stroke-opacity. Did you mean strokeOpacity?`.
The attribute names are adjusted according to [this](https://github.com/facebook/react/blob/master/src/browser/ui/dom/SVGDOMPropertyConfig.js#L67-L86).
=> Change attribute names to reactjs naming and add spreadMethod

core/src/main/scala/japgolly/scalajs/react/vdom/Implicits.scala, core/src/main/scala/japgolly/scalajs/react/vdom/Scalatags.scala, test/src/test/scala/japgolly/scalajs/react/CoreTest.scala
As stated at http://facebook.github.io/react/docs/forms.html, `value` / `defaultValue` of `multiple` `select` elements can be arrays, so I added support. Working properly on a local build.
=> Allow scalatags to accept js.Array as an attribute value

doc/USAGE.md
When I tried using just "react.js" this in a Play project I got this error:
JSLibResolveException: Some references to JS libraries could not be resolved:
- Ambiguous reference to a JS library: react.js
Possible paths found on the classpath:
- META-INF/resources/webjars/react/0.12.2/vendor/fbtransform/transforms/react.js
- META-INF/resources/webjars/react/0.12.2/react.js
originating from: client:compile
Specifying the more specific path solved it.
=> More specific jsDependency

core/src/main/scala/japgolly/scalajs/react/CallbackOption.scala
Hah, i was coing to contribute a `zip` for `Callback` and `CallbackOption` - seems you beat me to it. That leaves this:
`withFilter` is to use ifs for `CallbackOption` in for comprehensions without a warning (breaks my build since im normally using most of https://tpolecat.github.io/2014/04/11/scalac-flags.html )
=> withFilter for CallbackOption to enable if in for comprehensions

doc/CHANGELOG-0.10.md
Per your TODO in doc/CHANGELOG-0.10.md, I've added a table of the new, non-overloaded render* methods.
=> Add table of render* methods.

doc/USAGE.md
`focusState` was renamed to `zoom` in 0.9.2. Update docs to reflect new name.
=> s/focusState/zoom/g in USAGE.md

core/src/main/scala/japgolly/scalajs/react/Callback.scala, doc/changelog/0.10.4.md
Per discussion on gitter, this re-throws exceptions that are otherwise thrown out by Callback.future. I think this implementation less violates the principle of least surprise, but happy to discuss =p
=> Re-throw errors when discarding results via Callback.future

doc/changelog/0.10.5.md, extra/src/main/scala/japgolly/scalajs/react/extra/router/types.scala
- IE doesn't properly support BaseUrl.fromWindowOrigin, so until the scala-js-dom facade
represents the possible undefined state for dom.window.location.origin, one can use this
method which can be used a fallback once the dom type is updated
Fixes #249
=> Provide safer BaseUrl.fromWindowLocation methods

doc/TESTING.md
This seems to fix the example. I am having trouble with my component that doesn't take any props for that example so any help with that would be nice.
=> `assert` had to be `assertHtml` in Test Documentation

core/src/main/scala/japgolly/scalajs/react/vdom/SvgTags.scala, doc/changelog/0.11.2.md
First and foremost: Thank you very much for such an awesome library!
Now concerning the PR:
I would like to include HTML inside an SVG via `foreignObject`. Apparently, SVG tags are case-sensitive ([see my SO post for details](http://stackoverflow.com/questions/39504988/react-svg-html-inside-foreignobject-not-rendered)).
Obviously, the PR is more a selfish patch than a proper fix – probably many other SVG tags have the same problem. How should we approach this?
=> SVG tags are case sensitive

neo/src/main/scala/japgolly/scalajs/react/vdom/HtmlAttrs.scala
For #299. As collected from React's source code
There are no *Capture variants according to React's [official doc](https://facebook.github.io/react/docs/events.html).
```
The onMouseEnter and onMouseLeave events propagate from the element 
being left to the one being entered instead of ordinary bubbling and do not have 
a capture phase.
```
=> Added *Capture variant of react events (e.g. onClickCapture)

neo/src/main/scala/japgolly/scalajs/react/JsComponent.scala, neo/src/test/resources/component-es3.js, neo/src/test/scala/japgolly/scalajs/react/JsComponentTest.scala
Small change for neo. Supports using a js React component in a different namespace than global.
Also throws a more descriptive error message when the component constructor does not exist.
For example: 
```
JsComponent.byName[Props, ChildrenArg.Varargs, Props]("ReactLeaflet.Map")
```
=> Support for namespaces in JsComponent name.

README.md, doc/changelog/0.11.3.md, project/plugins.sbt
I wasn’t able to run the tests because I don’t have phantomjs but everything compiles fine without any warning.
=> Upgrade to Scala.js 0.6.13

doc/ROUTER.md
Having this link there would have saved me a few hours of searching.
=> Adding a link to a simple routing example.

.travis.yml, README.md, build.sbt, doc/EXTRA.md, doc/FP.md, doc/PERFORMANCE.md, doc/ROUTER.md, doc/TESTING.md, doc/USAGE.md, doc/changelog/0.11.4.md, project/Build.scala, project/plugins.sbt
This is the PR to address https://github.com/japgolly/scalajs-react/issues/354. Idea is to release a version of the scalajs-react 0.11.x series with the latest dependencies for scala.js (in this case its scala.js 0.6.16 which is the latest compatible version of Scalajs in the 0.6.x series)
Note that scala.js 0.6.16 is both backwards and forwards compatible with 0.6.15, hence why 0.6.15+ is the requirement, see https://www.scala-js.org/news/2017/04/29/announcing-scalajs-0.6.16/ for more info
@japgolly Does it make sense to bump JSDom as well? According to the release notes,
> It also adds support for jsdom v10.x (which contains breaking changes wrt. jsdom v9.x) and Scala 2.13.0-M1.
This is probably the main change for scala.js 0.6.16 vs 0.6.15
=> v0.11.4 with scala.js 0.6.16

doc/FP.md
Hi there,
Thanks for writing this library.  It kicks ass.  You're blog is interesting too!
One thing I got stumped on for quite a while was trying to work out why my `StateSnapshot` was not compiling when I tried to use Monocle lenses.  After some time I worked out that I was missing the macro paradise compiler plugin.  I thought I'd throw in a pull request to help others who make the same mistake.
I've expanded the necessary instructions in the docs to include this.  Feel free to comment and change.
Cheers,
Matt
=> Expand monocle ext dependency instructions

doc/INTEROP.md
[Partly] addresses https://github.com/japgolly/scalajs-react/issues/358 and elaborates the example to show off callback integration techniques.
I deliberately dumbed it down and didn't use `js.UndefOr` wrapper and function composition to demonstrate just the gist in a more beginner (e.g. me) friendly way.
=> Additional documentation for pure React callback interop

README.md
Hi, 
thanks for package!
It is really cool, that so solid ecosystem already exists around scalajs-react.
For me [diode](https://github.com/suzaku-io/diode) and [scalafiddle-editor](https://github.com/scalafiddle/scalafiddle-editor) projects were very helpful for understanding how to build frontend apps with scalajs-react.
I've added references to the packages in README.
=> Add references to diode and scalafiddle-editor in README

core/src/main/scala/japgolly/scalajs/react/vdom/SvgAttrs.scala
Been working with SVG recently and I've noticed a lot of warnings such as
`Warning: Unknown DOM property stroke-linejoin. Did you mean strokeLinejoin?`
This appears to be due to SvgAttrs being half-migrated.
Looking at the React source, it appears that the remaining "-" attrs are now supported using React camel case attrs.
https://github.com/facebook/react/blob/master/src/renderers/dom/shared/SVGDOMPropertyConfig.js
This pull request moves the remaining attrs to camel case to avoid the above warning.
=> Change remaining SVG attrs to React SVG attrs

README.md
Hi,
i've added reference to [scala-weather-app](https://github.com/malaman/scala-weather-app).
The app is pretty simple, but it might give some examples about how to use js/react.js components inside scalajs-react app.
=> add reference to scala-weather-app in README

cats/src/main/scala/japgolly/scalajs/react/internal/CatsReactState.scala
I may be in over my depth, but here goes.
I would like to use the ReactS monad along with ajax requests. To accomodate this, I've added some convenience functions into the Cats StateAccessRW extension.
These allow the monad to be used as such:
```scala
object Example {
case class State(list: List[String])
val ST = ReactS.Fix[State]
val home = ScalaComponent.builder[Unit]("Example")
.initialState(State(Nil))
.renderS { ($, s) =>
<.div(
^.onClick --> $.runStateFuture(appendExample),
<.ul(s.events.toTagMod(<.li(_)))
)
}
.componentDidMount(_.runStateFuture(appendExample))
.build
def appendExample: ReactST[Future, Home.State, Unit] =
ST.modM(s => Ajax.get("http://date.jsontest.com/") map (r => State(s.events :+ r.responseText)))
}
```
Hopefully there is nothing fundamentally wrong with using …
=> Add runStateFuture and runStateFnFuture functions

doc/changelog/1.2.1.md, extra/src/main/scala/japgolly/scalajs/react/extra/Ajax.scala
When using the Ajax helper to upload files, the onProgress event listener (which attaches to xhr.onprogress)  doesn't trigger. This is done separately through xhr.upload.onprogress. 
I've added onUploadProgress to the Ajax helper to attach such a listener. I was thinking if it would make sense to rename the old one to onDownloadProgress but that would break the existing API so it's maybe good enough.
=> added onUploadProgrss to Ajax helper

doc/changelog/1.3.2.md, extra/src/main/scala/japgolly/scalajs/react/extra/Ajax.scala
Add `onCompleteTry` to Ajax so that its easier to pattern match against ajax response, e.g.
```
Ajax(req.method, req.url)
.send(req.body)
.onCompleteTry { 
case Success(xhr) => ...
case Failure(AjaxException(xhr)) => ....
}
```
=> Add onCompleteHandle to Ajax

README.md
The scaladoc site is much improved in 2.12.   It would be nice if the default docs links went to that instead of the old 2.11.
=> Change API links to point to 2.12

doc/CALLBACK.md, doc/VDOM.md
Hi! I get started with scalajs-react through the docs and spotted a few typos.
=> Fix some typos in doc

core/src/main/scala/japgolly/scalajs/react/raw/Suspense.scala, doc/changelog/1.4.1.md
Fixes #522, see https://github.com/japgolly/scalajs-react/issues/522#issuecomment-472864459 and https://github.com/japgolly/scalajs-react/issues/522#issuecomment-472867501 for more details.
=> Fix the import of `raw.Suspense` when using a module system

core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala, doc/changelog/1.4.2.md, gh-pages/src/main/scala/ghpages/secret/tests/AsyncTest.scala, gh-pages/src/main/scala/ghpages/secret/tests/QuickTest.scala, test/src/test/scala/japgolly/scalajs/react/core/AsyncCallbackTest.scala
`Callback`s are meant to be repeatable in that they're supposed to perform the same action each time they're invoked. If you have a `Callback` that makes an AJAX call (especially if created via the `Ajax` helper), you should be able to invoke it multiple times (eg. to retry on failure) and have it make new calls each invocation. This isn't the case in 1.4.1 but this PR fixes this.
=> Fix AsyncCallback & Ajax repeatability

core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala, test/src/test/scala/japgolly/scalajs/react/core/AsyncCallbackTest.scala
Fixes #528. This is important for avoiding glitches when using Suspense with
external libraries (which often use Futures as a common interchange type for
async tasks). It's also nice to avoid the ScalaJS-React dependency in non-view
code.
=> Make AsyncCallback.fromFuture sync if the Future it is derived from is

project/Build.scala
Earlier version than 0.10.0 were released under a different organization
(From 'org.spire-math' to 'org.typelevel')
https://mvnrepository.com/artifact/org.spire-math/kind-projector
https://mvnrepository.com/artifact/org.typelevel/kind-projector
Helping @scala-steward to updated libraries 
This is blocking https://github.com/japgolly/scalajs-react/issues/556
=> Update kind-projector from 0.9.10 to 0.10.3

README.md
Hi
I created a scala-js version of the code from the tutorial from the official react site while trying to learn both react and scalajs-react in parallel.
I thought it might be useful to others attempting the same.
=> Add reference to 'Intro to React' tutorial in readme.

callback/src/main/scala-2/japgolly/scalajs/react/callback/CallbackOption.scala, callback/src/main/scala-3/japgolly/scalajs/react/callback/CallbackOption.scala, callback/src/main/scala/japgolly/scalajs/react/util/EffectCallback.scala, coreExtCats/src/main/scala/japgolly/scalajs/react/ReactCats.scala, coreExtCats/src/main/scala/japgolly/scalajs/react/internal/ReactCats.scala, coreExtCats/src/test/scala/japgolly/scalajs/react/ReactCatsCompilationTest.scala, coreExtCatsEffect/src/main/scala/japgolly/scalajs/react/util/EffectCatsEffect.scala, coreExtCatsEffect/src/test/scala/japgolly/scalajs/react/util/ReactCatsEffectCompilationTest.scala, doc/changelog/2.0.0-RCs.md, doc/changelog/2.0.0.md, util/src/main/scala/japgolly/scalajs/react/util/Effect.scala, util/src/main/scala/japgolly/scalajs/react/util/Monad.scala
- Derive `cats.MonadThrow[F]` when there's an implicit `Effect.Sync[F]`.
- Derive `cats.Monoid[F[A]]` when there's an implicit `Effect.Sync[F]` and `Monoid[A]`.
- Added `throwException` to `Dispatch` typeclass.
=> Derive cats.Monad+Monoid for Effect.Sync.

library/coreGeneric/src/main/scala/japgolly/scalajs/react/Reusability.scala, library/tests/src/test/scala/japgolly/scalajs/react/core/ReusabilityTest.scala
=> Add `Reusability` for component refs

library/coreGeneric/src/main/scala/japgolly/scalajs/react/vdom/SvgTags.scala
The current version renders the `clipPathTag` tag which isn't correct.
=> fix: Correct the clipPath tag

library/coreGeneric/src/main/scala/japgolly/scalajs/react/vdom/SvgAttrs.scala
key was missing from SVG attributes, requiring users to use the HTML one, which is a bit awkward.
=> Add react key to SVG attributes

doc/changelog/next.md, library/project/Lib.scala
When everything moved to the subdirectory I think it broke the mapping, I was playing around with something and just noticed it stopped correctly mapping sources.
=> Point at library subfolder

library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/CustomHook.scala
`shouldComponentUpdate` hook and `renderWithReuse` use an embedded class component to achieve reusability.
This PR changes the approach to the recommended use of `React.memo` for this purpose. This avoids having to mix functional and class components.
Furthermore, I'm having trouble making class components work with React 18. This unlocks the use of React 18 for apps with purely functional components.
=> Reusability in functional components via React.memo instead of class component

.github/workflows/release.yml, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/CustomHook.scala
Eager initialization resulted in errors in some cases.
Also, provide more memory to build releases.
=> Make reuse component lazy

library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/HookComponentBuilder.scala, library/tests/src/test/scala/japgolly/scalajs/react/core/HooksTest.scala
Components that only used the `useEffect` family of hooks didn't invoke the hooks.
=> Actually invoke init in components stuck in "first"

doc/changelog/2.1.2.md, doc/changelog/next.md, downstream-tests/scalafix.sbt, library/callback/src/main/scala-3/japgolly/scalajs/react/callback/CallbackOption.scala, library/callback/src/main/scala-3/japgolly/scalajs/react/callback/CallbackTo.scala, library/coreGeneric/src/main/scala-3/japgolly/scalajs/react/ReusabilityMacros.scala, library/coreGeneric/src/main/scala-3/japgolly/scalajs/react/component/builder/ComponentBuilderMacros.scala, library/project/Dependencies.scala, library/project/build.properties, library/project/plugins.sbt, library/scalafix.sbt, library/tests/src/test/scala/japgolly/scalajs/react/core/ScalaComponentTest.scala
I can't upgrade Scala 3 past 3.3.0. Starting with 3.3.1, the backend macro produces an error that I haven't been able to figure out how to fix.
=> Dependency updates

library/extra/src/main/scala/japgolly/scalajs/react/extra/router/Router.scala
This wraps the router state actions in [startTransition](https://react.dev/reference/react/useTransition#starttransition). This allows router updates to be non-blocking. React recommends all router updates to be wrapped in a transition.
I.e. if you click on 1 page, you can immediately navigate to another page without waiting for the first page to finish rendering.
~~I've wrapped 2 actions in `startTransition`, these made the most sense to me, but I'm not sure if both of them are necessary. The code is a bit complex 😅~~
=> Wrap router actions in startTransition

.envrc, .gitignore, downstream-tests/scalafix.sbt, flake.lock, flake.nix, library/callback/src/main/scala-3/japgolly/scalajs/react/callback/CallbackOption.scala, library/callback/src/main/scala-3/japgolly/scalajs/react/callback/CallbackTo.scala, library/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala, library/project/Dependencies.scala, library/project/plugins.sbt, library/scalafix.sbt
This PR allows users to define custom `Route`s which turn `Path`s into pages and viceversa, without requiring them to be build via the DSL. Of course, the old DSL still works.
Also: add flake.nix, update dependencies.
=> Allow custom route parsers

library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/Api.scala, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/Hooks.scala, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/UseCallbackBoilerplate.scala, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/react17.scala, library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/react18.scala, library/facadeMain/src/main/scala/japgolly/scalajs/react/facade/Hooks.scala, library/facadeMain/src/main/scala/japgolly/scalajs/react/facade/React.scala, library/project/GenHooks.scala, library/tests/src/test/scala/japgolly/scalajs/react/core/HooksTest.scala
Implements:
- `useDeferredValue`
- `useSyncExternalStore`
- `useInsertionEffect`
`useCallback` now accepts functions that return a sync value (before it only worked on functions that returned sync or async `Unit`).
=> Implement missing React 18 hooks, useCallback accepts non-unit afunctions
